# Generated by Django 3.1.4 on 2021-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20201227_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True, verbose_name='File Name')),
                ('file_uploaded', models.FileField(upload_to='media', verbose_name='File Upload')),
            ],
        ),
        migrations.AlterField(
            model_name='about_me',
            name='bout_me',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='About_me'),
        ),
    ]
